-- ============================================================================
-- Tasky - esquema inicial
-- Convencao: tabelas e colunas em snake_case portugues; enums como VARCHAR
-- com CHECK (evoluir um CHECK e mais simples que alterar um tipo ENUM).
-- ============================================================================

-- ----------------------------------------------------------------------------
-- usuario
-- ----------------------------------------------------------------------------
CREATE TABLE usuario (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email              VARCHAR(255) NOT NULL,
    senha_hash         VARCHAR(100) NOT NULL,
    nome_exibicao      VARCHAR(100) NOT NULL,
    fuso_horario       VARCHAR(64)  NOT NULL DEFAULT 'America/Sao_Paulo',
    hora_resumo_diario TIME,
    criado_em          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uk_usuario_email UNIQUE (email)
);

-- ----------------------------------------------------------------------------
-- modelo_dia / bloco_modelo / atribuicao_dia  (a rotina)
-- ----------------------------------------------------------------------------
CREATE TABLE modelo_dia (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT       NOT NULL,
    nome       VARCHAR(100) NOT NULL,
    padrao     BOOLEAN      NOT NULL DEFAULT FALSE,
    versao     BIGINT       NOT NULL DEFAULT 0,
    criado_em  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT fk_modelo_dia_usuario FOREIGN KEY (usuario_id)
        REFERENCES usuario (id) ON DELETE CASCADE
);
CREATE INDEX ix_modelo_dia_usuario ON modelo_dia (usuario_id);

CREATE TABLE bloco_modelo (
    id                            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    modelo_dia_id                 BIGINT       NOT NULL,
    titulo                        VARCHAR(200) NOT NULL,
    hora_inicio                   TIME         NOT NULL,
    hora_fim                      TIME         NOT NULL,
    cor                           VARCHAR(20),
    ordem                         INTEGER      NOT NULL DEFAULT 0,
    minutos_antecedencia_lembrete INTEGER,
    versao                        BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT fk_bloco_modelo_modelo_dia FOREIGN KEY (modelo_dia_id)
        REFERENCES modelo_dia (id) ON DELETE CASCADE,
    -- Bloco atravessando a meia-noite nao e suportado no MVP.
    CONSTRAINT ck_bloco_modelo_horario CHECK (hora_fim > hora_inicio),
    CONSTRAINT ck_bloco_modelo_antecedencia
        CHECK (minutos_antecedencia_lembrete IS NULL OR minutos_antecedencia_lembrete >= 0)
);
CREATE INDEX ix_bloco_modelo_modelo_dia ON bloco_modelo (modelo_dia_id, ordem);

CREATE TABLE atribuicao_dia (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id    BIGINT     NOT NULL,
    dia_semana    VARCHAR(3) NOT NULL,
    modelo_dia_id BIGINT     NOT NULL,
    CONSTRAINT fk_atribuicao_dia_usuario FOREIGN KEY (usuario_id)
        REFERENCES usuario (id) ON DELETE CASCADE,
    -- RESTRICT: deletar um modelo em uso deve ser bloqueado.
    CONSTRAINT fk_atribuicao_dia_modelo FOREIGN KEY (modelo_dia_id)
        REFERENCES modelo_dia (id) ON DELETE RESTRICT,
    CONSTRAINT uk_atribuicao_dia UNIQUE (usuario_id, dia_semana),
    CONSTRAINT ck_atribuicao_dia_semana
        CHECK (dia_semana IN ('SEG','TER','QUA','QUI','SEX','SAB','DOM'))
);

-- ----------------------------------------------------------------------------
-- habito / registro_habito
-- ----------------------------------------------------------------------------
CREATE TABLE habito (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id     BIGINT       NOT NULL,
    nome           VARCHAR(100) NOT NULL,
    icone          VARCHAR(40),
    cor            VARCHAR(20),
    tipo_agenda    VARCHAR(20)  NOT NULL,
    dias_semana    VARCHAR(40),
    meta_semanal   INTEGER,
    hora_preferida TIME,
    hora_lembrete  TIME,
    arquivado_em   TIMESTAMPTZ,
    versao         BIGINT       NOT NULL DEFAULT 0,
    criado_em      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT fk_habito_usuario FOREIGN KEY (usuario_id)
        REFERENCES usuario (id) ON DELETE CASCADE,
    CONSTRAINT ck_habito_tipo_agenda
        CHECK (tipo_agenda IN ('DIARIO','DIAS_SEMANA','VEZES_POR_SEMANA')),
    CONSTRAINT ck_habito_meta_semanal
        CHECK (meta_semanal IS NULL OR meta_semanal BETWEEN 1 AND 7),
    -- Cada tipo de agenda exige o seu campo de configuracao.
    CONSTRAINT ck_habito_agenda_coerente CHECK (
           (tipo_agenda = 'DIARIO')
        OR (tipo_agenda = 'DIAS_SEMANA'      AND dias_semana  IS NOT NULL)
        OR (tipo_agenda = 'VEZES_POR_SEMANA' AND meta_semanal IS NOT NULL)
    )
);
CREATE INDEX ix_habito_usuario ON habito (usuario_id, arquivado_em);

CREATE TABLE registro_habito (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    habito_id    BIGINT      NOT NULL,
    data         DATE        NOT NULL,
    status       VARCHAR(10) NOT NULL,
    concluido_em TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_registro_habito_habito FOREIGN KEY (habito_id)
        REFERENCES habito (id) ON DELETE CASCADE,
    CONSTRAINT uk_registro_habito UNIQUE (habito_id, data),
    CONSTRAINT ck_registro_habito_status CHECK (status IN ('FEITO','PULADO'))
);
CREATE INDEX ix_registro_habito_data ON registro_habito (habito_id, data DESC);

-- ----------------------------------------------------------------------------
-- tarefa
-- ----------------------------------------------------------------------------
CREATE TABLE tarefa (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id         BIGINT        NOT NULL,
    titulo             VARCHAR(200)  NOT NULL,
    observacoes        VARCHAR(5000),
    prioridade         VARCHAR(10)   NOT NULL DEFAULT 'MEDIA',
    minutos_estimados  INTEGER,
    data_limite        DATE,
    data_planejada     DATE,
    hora_planejada     TIME,
    bloco_planejado_id BIGINT,
    status             VARCHAR(10)   NOT NULL DEFAULT 'A_FAZER',
    concluido_em       TIMESTAMPTZ,
    hora_lembrete      TIME,
    versao             BIGINT        NOT NULL DEFAULT 0,
    criado_em          TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT fk_tarefa_usuario FOREIGN KEY (usuario_id)
        REFERENCES usuario (id) ON DELETE CASCADE,
    -- Apagar o bloco nao apaga a tarefa: ela continua no dia, sem bloco.
    CONSTRAINT fk_tarefa_bloco FOREIGN KEY (bloco_planejado_id)
        REFERENCES bloco_modelo (id) ON DELETE SET NULL,
    CONSTRAINT ck_tarefa_prioridade CHECK (prioridade IN ('BAIXA','MEDIA','ALTA')),
    CONSTRAINT ck_tarefa_status     CHECK (status IN ('A_FAZER','FEITA','CANCELADA')),
    CONSTRAINT ck_tarefa_minutos    CHECK (minutos_estimados IS NULL OR minutos_estimados > 0)
);
CREATE INDEX ix_tarefa_usuario_dia    ON tarefa (usuario_id, data_planejada, status);
CREATE INDEX ix_tarefa_usuario_status ON tarefa (usuario_id, status);

-- ----------------------------------------------------------------------------
-- lembrete_dia  (lembretes materializados com horario absoluto)
-- ----------------------------------------------------------------------------
CREATE TABLE lembrete_dia (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id  BIGINT       NOT NULL,
    disparar_em TIMESTAMPTZ  NOT NULL,
    tipo_origem VARCHAR(10)  NOT NULL,
    origem_id   BIGINT,
    data_ref    DATE         NOT NULL,
    titulo      VARCHAR(200) NOT NULL,
    corpo       VARCHAR(500),
    status      VARCHAR(10)  NOT NULL DEFAULT 'PENDENTE',
    tentativas  INTEGER      NOT NULL DEFAULT 0,
    enviado_em  TIMESTAMPTZ,
    criado_em   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT fk_lembrete_dia_usuario FOREIGN KEY (usuario_id)
        REFERENCES usuario (id) ON DELETE CASCADE,
    CONSTRAINT ck_lembrete_dia_tipo
        CHECK (tipo_origem IN ('BLOCO','HABITO','TAREFA','RESUMO')),
    CONSTRAINT ck_lembrete_dia_status
        CHECK (status IN ('PENDENTE','ENVIADO','FALHOU','CANCELADO')),
    -- NULLS NOT DISTINCT e essencial: o lembrete de RESUMO tem origem_id nulo
    -- e, sem isso, poderia ser materializado varias vezes no mesmo dia.
    CONSTRAINT uk_lembrete_dia_origem
        UNIQUE NULLS NOT DISTINCT (usuario_id, tipo_origem, origem_id, data_ref)
);
-- Indice da query do despachante (roda a cada 60s).
CREATE INDEX ix_lembrete_dia_despacho ON lembrete_dia (status, disparar_em);

-- ----------------------------------------------------------------------------
-- inscricao_push  (uma por dispositivo)
-- ----------------------------------------------------------------------------
CREATE TABLE inscricao_push (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT        NOT NULL,
    endpoint   VARCHAR(1000) NOT NULL,
    p256dh     VARCHAR(255)  NOT NULL,
    auth       VARCHAR(255)  NOT NULL,
    user_agent VARCHAR(400),
    visto_em   TIMESTAMPTZ,
    criado_em  TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT fk_inscricao_push_usuario FOREIGN KEY (usuario_id)
        REFERENCES usuario (id) ON DELETE CASCADE,
    CONSTRAINT uk_inscricao_push_endpoint UNIQUE (endpoint)
);
CREATE INDEX ix_inscricao_push_usuario ON inscricao_push (usuario_id);

-- ----------------------------------------------------------------------------
-- refresh_token  (rotacao com familia, para revogar em cadeia)
-- ----------------------------------------------------------------------------
CREATE TABLE refresh_token (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id  BIGINT       NOT NULL,
    token_hash  VARCHAR(100) NOT NULL,
    familia     UUID         NOT NULL,
    expira_em   TIMESTAMPTZ  NOT NULL,
    revogado_em TIMESTAMPTZ,
    criado_em   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT fk_refresh_token_usuario FOREIGN KEY (usuario_id)
        REFERENCES usuario (id) ON DELETE CASCADE,
    CONSTRAINT uk_refresh_token_hash UNIQUE (token_hash)
);
CREATE INDEX ix_refresh_token_usuario ON refresh_token (usuario_id);
CREATE INDEX ix_refresh_token_familia ON refresh_token (familia);
